/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agendareuniones;

import javax.swing.JOptionPane;

/**
 *
 * @author Estuardo
 */
public class panelAgenda extends javax.swing.JFrame {
    
    Salas salas = new Salas();
    int h;
    int d;
    int s;
    int salaEnConsulta;

    /**
     * Creates new form panelAgenda
     */
    public panelAgenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnOcupar9 = new javax.swing.JButton();
        btnOcupar10 = new javax.swing.JButton();
        btnOcupar11 = new javax.swing.JButton();
        btnOcupar12 = new javax.swing.JButton();
        btnOcupar13 = new javax.swing.JButton();
        btnOcupar14 = new javax.swing.JButton();
        btnOcupar15 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblNombreSala = new javax.swing.JLabel();
        cbxDia = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnConsultaSala = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblEstado9 = new javax.swing.JLabel();
        lblEstado10 = new javax.swing.JLabel();
        lblEstado11 = new javax.swing.JLabel();
        lblEstado12 = new javax.swing.JLabel();
        lblEstado13 = new javax.swing.JLabel();
        lblEstado14 = new javax.swing.JLabel();
        lblEstado15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnHecho = new javax.swing.JButton();
        btnLimpiarAgenda = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 250));
        setUndecorated(true);

        jPanel1.setLayout(null);

        btnOcupar9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOcupar9.setText("OCUPAR");
        btnOcupar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcupar9ActionPerformed(evt);
            }
        });
        jPanel1.add(btnOcupar9);
        btnOcupar9.setBounds(12, 36, 104, 25);

        btnOcupar10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOcupar10.setText("OCUPAR");
        btnOcupar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcupar10ActionPerformed(evt);
            }
        });
        jPanel1.add(btnOcupar10);
        btnOcupar10.setBounds(10, 80, 104, 25);

        btnOcupar11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOcupar11.setText("OCUPAR");
        btnOcupar11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcupar11ActionPerformed(evt);
            }
        });
        jPanel1.add(btnOcupar11);
        btnOcupar11.setBounds(12, 117, 104, 25);

        btnOcupar12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOcupar12.setText("OCUPAR");
        btnOcupar12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcupar12ActionPerformed(evt);
            }
        });
        jPanel1.add(btnOcupar12);
        btnOcupar12.setBounds(10, 160, 104, 25);

        btnOcupar13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOcupar13.setText("OCUPAR");
        btnOcupar13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcupar13ActionPerformed(evt);
            }
        });
        jPanel1.add(btnOcupar13);
        btnOcupar13.setBounds(12, 198, 104, 25);

        btnOcupar14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOcupar14.setText("OCUPAR");
        btnOcupar14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcupar14ActionPerformed(evt);
            }
        });
        jPanel1.add(btnOcupar14);
        btnOcupar14.setBounds(12, 236, 104, 25);

        btnOcupar15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOcupar15.setText("OCUPAR");
        btnOcupar15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcupar15ActionPerformed(evt);
            }
        });
        jPanel1.add(btnOcupar15);
        btnOcupar15.setBounds(12, 275, 104, 25);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Sala:");

        lblNombreSala.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        cbxDia.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cbxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miercoles", "Jueves", "Viernes" }));
        cbxDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDiaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Dia:");
        jLabel2.setToolTipText("");

        btnConsultaSala.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        btnConsultaSala.setForeground(new java.awt.Color(22, 222, 22));
        btnConsultaSala.setText("CONSULTAR");
        btnConsultaSala.setPreferredSize(new java.awt.Dimension(143, 58));
        btnConsultaSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaSalaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HORARIO");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Estado");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("9:00 - 10:00");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("10:00 - 11:00");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("11:00 - 12:00");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("12:00 - 13:00");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("13:00 - 14:00");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("14:00 - 15:00");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("15:00 - 16:00");

        lblEstado9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEstado9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstado9.setText("Consulte");

        lblEstado10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEstado10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstado10.setText("Consulte");

        lblEstado11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEstado11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstado11.setText("Consulte");

        lblEstado12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEstado12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstado12.setText("Consulte");

        lblEstado13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEstado13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstado13.setText("Consulte");

        lblEstado14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEstado14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstado14.setText("Consulte");

        lblEstado15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEstado15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstado15.setText("Consulte");

        btnHecho.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnHecho.setText("HECHO");
        btnHecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHechoActionPerformed(evt);
            }
        });

        btnLimpiarAgenda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpiarAgenda.setText("Limpiar Agenda");
        btnLimpiarAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarAgendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHecho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLimpiarAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLimpiarAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnHecho, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 60, 255));
        jButton1.setText("AYUDA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lblNombreSala, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxDia, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnConsultaSala, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEstado9, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(lblEstado10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEstado11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEstado12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEstado13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEstado14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEstado15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(309, 309, 309)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombreSala, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(cbxDia))))
                        .addGap(51, 51, 51))
                    .addComponent(btnConsultaSala, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblEstado9)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblEstado10)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblEstado11)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblEstado12)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblEstado13)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblEstado14)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblEstado15))
                                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDiaActionPerformed
        // TODO add your handling code here:
        btnOcupar9.setVisible(true);
        btnOcupar10.setVisible(true);
        btnOcupar11.setVisible(true);
        btnOcupar12.setVisible(true);
        btnOcupar13.setVisible(true);
        btnOcupar14.setVisible(true);
        btnOcupar15.setVisible(true);
        lblEstado9.setText("Consulte");
        lblEstado10.setText("Consulte");
        lblEstado11.setText("Consulte");
        lblEstado12.setText("Consulte");
        lblEstado13.setText("Consulte");
        lblEstado14.setText("Consulte");
        lblEstado15.setText("Consulte");
    }//GEN-LAST:event_cbxDiaActionPerformed
    
    private void btnConsultaSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaSalaActionPerformed
        // TODO add your handling code here:
        panelPrincipal frame = new panelPrincipal();
        d = cbxDia.getSelectedIndex();
        s = salaEnConsulta;
        
        try{
        if(salas.agenda[0][d][s] == 1){
            lblEstado9.setText("Ocupado");
            btnOcupar9.setVisible(false);
            //System.out.println(salaEnConsulta);
        }else{
            lblEstado9.setText("Libre");
            btnOcupar9.setVisible(true);
        }
            
        }catch(Exception e){
            return;
        }
        
        try{
        if(salas.agenda[1][d][s] == 1){
            lblEstado10.setText("Ocupado");
            btnOcupar10.setVisible(false);
        }else{
            lblEstado10.setText("Libre");
            btnOcupar10.setVisible(true);
        }
            
        }catch(Exception e){
            return;
        }
        
        try{
        if(salas.agenda[2][d][s] == 1){
            lblEstado11.setText("Ocupado");
            btnOcupar11.setVisible(false);
        }else{
            lblEstado11.setText("Libre");
            btnOcupar11.setVisible(true);
        }
            
        }catch(Exception e){
            return;
        }
        
        try{
        if(salas.agenda[3][d][s] == 1){
            lblEstado12.setText("Ocupado");
            btnOcupar12.setVisible(false);
        }else{
            lblEstado12.setText("Libre");
            btnOcupar12.setVisible(true);
        }
            
        }catch(Exception e){
            return;
        }
        
        try{
        if(salas.agenda[4][d][s] == 1){
            lblEstado13.setText("Ocupado");
            btnOcupar13.setVisible(false);
        }else{
            lblEstado13.setText("Libre");
            btnOcupar13.setVisible(true);
        }
            
        }catch(Exception e){
            return;
        }
        
        try{
        if(salas.agenda[5][d][s] == 1){
            lblEstado14.setText("Ocupado");
            btnOcupar14.setVisible(false);
        }else{
            lblEstado14.setText("Libre");
            btnOcupar14.setVisible(true);
        }
            
        }catch(Exception e){
            return;
        }
        
        try{
        if(salas.agenda[6][d][s] == 1){
            lblEstado15.setText("Ocupado");
            btnOcupar15.setVisible(false);
        }else{
            lblEstado15.setText("Libre");
            btnOcupar15.setVisible(true);
        }
            
        }catch(Exception e){
            return;
        }
        
    }//GEN-LAST:event_btnConsultaSalaActionPerformed

    private void btnHechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHechoActionPerformed
        // TODO add your handling code here:
        dispose();
        btnOcupar9.setVisible(true);
        btnOcupar10.setVisible(true);
        btnOcupar11.setVisible(true);
        btnOcupar12.setVisible(true);
        btnOcupar13.setVisible(true);
        btnOcupar14.setVisible(true);
        btnOcupar15.setVisible(true);
        lblEstado9.setText("Consulte");
        lblEstado10.setText("Consulte");
        lblEstado11.setText("Consulte");
        lblEstado12.setText("Consulte");
        lblEstado13.setText("Consulte");
        lblEstado14.setText("Consulte");
        lblEstado15.setText("Consulte");
    }//GEN-LAST:event_btnHechoActionPerformed

    private void btnOcupar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcupar9ActionPerformed
        // TODO add your handling code here:
        panelPrincipal frame = new panelPrincipal();
        d = cbxDia.getSelectedIndex();
        s = salaEnConsulta;
        salas.agenda[0][d][s] = 1;
        btnOcupar9.setVisible(false);
        lblEstado9.setText("Ocupado");
        
    }//GEN-LAST:event_btnOcupar9ActionPerformed

    private void btnOcupar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcupar10ActionPerformed
        // TODO add your handling code here:
        panelPrincipal frame = new panelPrincipal();
        d = cbxDia.getSelectedIndex();
        s = salaEnConsulta;
        salas.agenda[1][d][s] = 1;
        btnOcupar10.setVisible(false);
        lblEstado10.setText("Ocupado");
    }//GEN-LAST:event_btnOcupar10ActionPerformed

    private void btnOcupar11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcupar11ActionPerformed
        // TODO add your handling code here:
        panelPrincipal frame = new panelPrincipal();
        d = cbxDia.getSelectedIndex();
        s = salaEnConsulta;
        salas.agenda[2][d][s] = 1;
        btnOcupar11.setVisible(false);
        lblEstado11.setText("Ocupado");
    }//GEN-LAST:event_btnOcupar11ActionPerformed

    private void btnOcupar12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcupar12ActionPerformed
        // TODO add your handling code here:
        panelPrincipal frame = new panelPrincipal();
        d = cbxDia.getSelectedIndex();
        s = salaEnConsulta;
        salas.agenda[3][d][s] = 1;
        btnOcupar12.setVisible(false);
        lblEstado12.setText("Ocupado");
    }//GEN-LAST:event_btnOcupar12ActionPerformed

    private void btnOcupar13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcupar13ActionPerformed
        // TODO add your handling code here:
        panelPrincipal frame = new panelPrincipal();
        d = cbxDia.getSelectedIndex();
        s = salaEnConsulta;
        salas.agenda[4][d][s] = 1;
        btnOcupar13.setVisible(false);
        lblEstado13.setText("Ocupado");
    }//GEN-LAST:event_btnOcupar13ActionPerformed

    private void btnOcupar14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcupar14ActionPerformed
        // TODO add your handling code here:
        panelPrincipal frame = new panelPrincipal();
        d = cbxDia.getSelectedIndex();
        s = salaEnConsulta;
        salas.agenda[5][d][s] = 1;
        btnOcupar14.setVisible(false);
        lblEstado14.setText("Ocupado");
    }//GEN-LAST:event_btnOcupar14ActionPerformed

    private void btnOcupar15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcupar15ActionPerformed
        // TODO add your handling code here:
        panelPrincipal frame = new panelPrincipal();
        d = cbxDia.getSelectedIndex();
        s = salaEnConsulta;
        salas.agenda[6][d][s] = 1;
        btnOcupar15.setVisible(false);
        lblEstado15.setText("Ocupado");
    }//GEN-LAST:event_btnOcupar15ActionPerformed

    private void btnLimpiarAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarAgendaActionPerformed
        // TODO add your handling code here:
        salas.resetAgenda();
        btnOcupar9.setVisible(true);
        btnOcupar10.setVisible(true);
        btnOcupar11.setVisible(true);
        btnOcupar12.setVisible(true);
        btnOcupar13.setVisible(true);
        btnOcupar14.setVisible(true);
        btnOcupar15.setVisible(true);
    }//GEN-LAST:event_btnLimpiarAgendaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, " -CONSULTAR: Muestra el ESTATUS de la sala en cada HORARIO del dia seleccionado \n\n"
                                          + " -DIA: Despliega la lista de dias disponibles \n\n"
                                          + " -OCUPAR: Cambia el estatus de la sala a OCUPADO en el horario indicado\n\n"
                                          + " -HECHO: Regresa al menú principal\n\n"
                                          + " -Limpiar Agenda: Reinicia por completo todos los horarios\n\n");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnConsultaSala;
    private javax.swing.JButton btnHecho;
    private javax.swing.JButton btnLimpiarAgenda;
    public javax.swing.JButton btnOcupar10;
    public javax.swing.JButton btnOcupar11;
    public javax.swing.JButton btnOcupar12;
    public javax.swing.JButton btnOcupar13;
    public javax.swing.JButton btnOcupar14;
    public javax.swing.JButton btnOcupar15;
    public javax.swing.JButton btnOcupar9;
    private javax.swing.JComboBox<String> cbxDia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel lblEstado10;
    public javax.swing.JLabel lblEstado11;
    public javax.swing.JLabel lblEstado12;
    public javax.swing.JLabel lblEstado13;
    public javax.swing.JLabel lblEstado14;
    public javax.swing.JLabel lblEstado15;
    public javax.swing.JLabel lblEstado9;
    public javax.swing.JLabel lblNombreSala;
    // End of variables declaration//GEN-END:variables
}
