/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agendareuniones;

import javax.swing.ImageIcon;

/**
 *
 * @author Estuardo
 */
public class panelPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form panelPrincipal
     */
    public panelPrincipal() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../icons/chocolate.png")).getImage());
    }
    panelAgenda formAgenda = new panelAgenda();
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalaA1 = new javax.swing.JButton();
        btnSalaA2 = new javax.swing.JButton();
        btnSalaA3 = new javax.swing.JButton();
        btnSalaB1 = new javax.swing.JButton();
        btnSalaB2 = new javax.swing.JButton();
        btnSalaB3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CHOCOLATES SIERRA - Control de Salas");
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setLocation(new java.awt.Point(150, 150));
        setMaximumSize(new java.awt.Dimension(765, 560));
        setMinimumSize(new java.awt.Dimension(765, 560));
        setPreferredSize(new java.awt.Dimension(765, 560));
        getContentPane().setLayout(null);

        btnSalaA1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        btnSalaA1.setText("SALA A-1");
        btnSalaA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalaA1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalaA1);
        btnSalaA1.setBounds(60, 120, 170, 90);

        btnSalaA2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        btnSalaA2.setText("SALA A-2");
        btnSalaA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalaA2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalaA2);
        btnSalaA2.setBounds(60, 260, 170, 90);

        btnSalaA3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        btnSalaA3.setText("SALA A-3");
        btnSalaA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalaA3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalaA3);
        btnSalaA3.setBounds(60, 400, 170, 90);

        btnSalaB1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        btnSalaB1.setText("SALA B-1");
        btnSalaB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalaB1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalaB1);
        btnSalaB1.setBounds(530, 120, 170, 90);

        btnSalaB2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        btnSalaB2.setText("SALA B-2");
        btnSalaB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalaB2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalaB2);
        btnSalaB2.setBounds(530, 260, 170, 90);

        btnSalaB3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        btnSalaB3.setText("SALA B-3");
        btnSalaB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalaB3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalaB3);
        btnSalaB3.setBounds(530, 400, 170, 90);

        jLabel2.setBackground(new java.awt.Color(222, 195, 172));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Primer Nivel");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 60, 170, 30);

        jLabel3.setBackground(new java.awt.Color(222, 195, 172));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Segundo Nivel");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(530, 60, 170, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salas-reuniones-officehelp.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 760, 530);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalaA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalaA1ActionPerformed
        // TODO add your handling code here:
        formAgenda.lblNombreSala.setText("A-1");
        formAgenda.salaEnConsulta = 0;
        System.out.println(formAgenda.salaEnConsulta);
        formAgenda.setVisible(true);
    }//GEN-LAST:event_btnSalaA1ActionPerformed

    private void btnSalaA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalaA3ActionPerformed
        // TODO add your handling code here:
        formAgenda.lblNombreSala.setText("A-3");
        formAgenda.salaEnConsulta = 2;
        System.out.println(formAgenda.salaEnConsulta);
        formAgenda.setVisible(true);
    }//GEN-LAST:event_btnSalaA3ActionPerformed

    private void btnSalaA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalaA2ActionPerformed
        // TODO add your handling code here:
        formAgenda.lblNombreSala.setText("A-2");
        formAgenda.salaEnConsulta = 1;
        System.out.println(formAgenda.salaEnConsulta);
        formAgenda.setVisible(true);
    }//GEN-LAST:event_btnSalaA2ActionPerformed

    private void btnSalaB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalaB1ActionPerformed
        // TODO add your handling code here:
        formAgenda.lblNombreSala.setText("B-1");
        formAgenda.salaEnConsulta = 3;
        System.out.println(formAgenda.salaEnConsulta);
        formAgenda.setVisible(true);
    }//GEN-LAST:event_btnSalaB1ActionPerformed

    private void btnSalaB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalaB2ActionPerformed
        // TODO add your handling code here:
        formAgenda.lblNombreSala.setText("B-2");
        formAgenda.salaEnConsulta = 4;
        System.out.println(formAgenda.salaEnConsulta);
        formAgenda.setVisible(true);
    }//GEN-LAST:event_btnSalaB2ActionPerformed

    private void btnSalaB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalaB3ActionPerformed
        // TODO add your handling code here:
        formAgenda.lblNombreSala.setText("B-3");
        formAgenda.salaEnConsulta = 5;
        System.out.println(formAgenda.salaEnConsulta);
        formAgenda.setVisible(true);
    }//GEN-LAST:event_btnSalaB3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalaA1;
    private javax.swing.JButton btnSalaA2;
    private javax.swing.JButton btnSalaA3;
    private javax.swing.JButton btnSalaB1;
    private javax.swing.JButton btnSalaB2;
    private javax.swing.JButton btnSalaB3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
